---
- name: reload systemd
  command: systemctl daemon-reload

- name: restart clash
  service:
    name: 'clash'
    state: 'restarted'
    enabled: 'yes'

- name: netfilter-persistent
  command: netfilter-persistent save
