---
- name: create docker-qbittorrent compose dir
  file:
    path: /root/docker-qbittorrent
    state: directory

- name: upload compose file
  template:
    src: 'docker-compose.yml'
    dest: '/root/docker-qbittorrent/docker-compose.yml'

- name: upload app image files
  copy:
    src: '{{ role_path }}/files/{{ item }}'
    dest: '/root/docker-qbittorrent'
  loop:
    - app

- name: Start docker-qbittorrent
  command:
    cmd: docker-compose up -d
    chdir: /root/docker-qbittorrent
