---
- hosts: voyager
  become: true
  gather_facts: false

  pre_tasks:
    - raw: sudo apt-get -y install python-simplejson
    - action: setup

- hosts: voyager
  vars_files:
    - secrets.yml
  roles:
    - router
