---
- name: clone git repository
  git:
    repo: 'https://github.com/discourse/discourse_docker.git'
    dest: /var/discourse

- name: upload container definitions
  template:
    src: 'container.yml'
    dest: '/var/discourse/containers/{{ item.name }}.yml'
  notify: rebuild discourse
  register: definitions
  with_items: '{{ discourse }}'

- name: upload nginx configuration
  template:
    src: 'nginx.conf'
    dest: '/etc/nginx/sites-enabled/{{ item.name }}.conf'
  notify: restart nginx
  with_items: '{{ discourse }}'
