---
- name: add apt repository key
  apt_key:
    url: '{{ docker_mirror_url | default("https://download.docker.com/linux/ubuntu") }}/gpg'

- name: add apt repository
  apt_repository:
    repo: 'deb [arch=amd64] {{ docker_mirror_url | default("https://download.docker.com/linux/ubuntu") }} {{ ansible_lsb.codename | lower }} stable'
    update_cache: yes

- name: install apt packages
  apt:
    name: docker-ce

- name: setup docker registry mirror
  template:
    src: daemon.json
    dest: /etc/docker/daemon.json
  when: docker_registry_url is defined
  notify: restart docker
