---
samba_hostname: Infinity
samba_root: /storage
samba_home_root: /storage/private/homes
samba_backup_root: /storage/backups
samba_timemachine_root: /storage/backups/timemachines
samba_users:
  - name: jysperm
    time_machine_quota: 512GB
smb_conf: |
  [Home]
    path = /storage/private/homes/%U
    writeable = yes
    valid users = jysperm

  [NextCloud]
    path = /storage/nextcloud/data/%U/files
    writeable = yes
    valid users = @staff
    force user = www-data

  [TimeMachine]
    path = /storage/backups/timemachines/%U
    writable = yes
    valid users = @staff

    durable handles = yes
    kernel oplocks = no
    kernel share modes = no
    posix locking = no
    vfs objects = catia fruit streams_xattr
    ea support = yes
    inherit acls = yes
    fruit:time machine = yes

  [Backup]
    path = /storage/backups/%U
    writeable = yes
    valid users = jysperm

  [VideoWorks]
    path = /storage/shares/VideoWorks
    writeable = yes
    valid users = @staff
    force group = staff
    create mask = 0775

  [Resources]
    path = /storage/public/Resources
    guest ok = yes
    write list = @staff
    force group = +staff
    create mask = 0775
