---
samba_hostname: nas
samba_root: /data
samba_home_root: /data/private/homes
samba_users:
  - name: kchou
smb_conf: |
  [Home]
    path = /data/private/homes/kchou
    writeable = yes
    valid users = kchou

  [NextCloud]
    path = /data/nextcloud/data/admin/files
    writeable = yes
    valid users = kchou
    force user = www-data
