---
- name: add apt repository
  apt_repository:
    repo: 'ppa:nginx/stable'
    update_cache: yes

- name: install apt packages
  apt: name=nginx

- name: upload nginx main config
  template: src=nginx.conf dest=/etc/nginx/nginx.conf
  notify: restart nginx

- name: delete nginx built-in default site
  file: path=/etc/nginx/sites-enabled/default state=absent

- name: upload nginx default site
  template: src=default.conf dest=/etc/nginx/sites-enabled/default.conf

- name: upload nginx resource file
  copy: src={{role_path}}/files/holding dest=/var/www

- name: upload nginx site config
  template: src={{item}} dest=/etc/nginx/sites-enabled/{{item | basename}}
  notify: restart nginx
  with_fileglob:
    - nginx-sites/{{ansible_hostname}}/*
