---
clash_release: 0.14.0
redir_port: '7892'
http_proxy_port: '8118'
wan_interface: 'enp1s0'
lan_interface: 'brlan'
lan_gateway_ip: '10.0.0.1'
lan_gateway_cidr: '10.0.0.1/24'
lan_subnet: '10.0.0.1/24'
lan_dhcp_range: '10.0.0.1,10.0.0.255,12h'
clash_proxy_ports: [10292, 30292, 36292, 48292, 54292]
clash_dashbiard_secret: ''
allowed_imcome_ports: [22, 5000]

clash_proxies: |
  Proxy:
    - { name: 'Some Proxy', type: 'ss', server: '1.2.3.4', port: 12345, cipher: 'aes-128-gcm',password :'123456' }

  Proxy Group:
    - { name: "Proxy", type: select, proxies: ['Some Proxy']}
    - { name: "CNProxy", type: select, proxies: [DIRECT, Proxy] }
    - { name: "Netflix", type: select, proxies: [Proxy, DIRECT] }
    - { name: "Hijacking", type: select, proxies: [REJECT, DIRECT] }
