---
- name: install apt packages
  apt: name={{item}}
  with_items:
    - python-pip
    - python-m2crypto

- name: install python version of shadowsocks
  pip: name=shadowsocks

- name: create config file
  template: src=config.json dest=/root/config.json
  notify: restart shadowsocks

- name: create cronjob to start shadowsocks
  cron: name=shadowsocks special_time=reboot job='ssserver -c /root/config.json -d start'

- name: tweak sysctl
  sysctl: name="{{item.name}}"
          value="{{item.value}}"
          ignoreerrors=yes
  with_items:
    - { "name": "fs.file-max", "value": "51200" }
    - { "name": "net.core.rmem_max", "value": "67108864" }
    - { "name": "net.core.wmem_max", "value": "67108864" }
    - { "name": "net.core.rmem_default", "value": "65536" }
    - { "name": "net.core.wmem_default", "value": "65536" }
    - { "name": "net.core.netdev_max_backlog", "value": "4096" }
    - { "name": "net.core.somaxconn", "value": "4096" }
    - { "name": "net.ipv4.tcp_syncookies", "value": "1" }
    - { "name": "net.ipv4.tcp_tw_reuse", "value": "1" }
    - { "name": "net.ipv4.tcp_tw_recycle", "value": "0" }
    - { "name": "net.ipv4.tcp_fin_timeout", "value": "30" }
    - { "name": "net.ipv4.tcp_keepalive_time", "value": "1200" }
    - { "name": "net.ipv4.ip_local_port_range", "value": "10000 65000" }
    - { "name": "net.ipv4.tcp_max_syn_backlog", "value": "4096" }
    - { "name": "net.ipv4.tcp_max_tw_buckets", "value": "5000" }
    - { "name": "net.ipv4.tcp_fastopen", "value": "3" }
    - { "name": "net.ipv4.tcp_rmem", "value": "4096 87380 67108864" }
    - { "name": "net.ipv4.tcp_wmem", "value": "4096 65536 67108864" }
    - { "name": "net.ipv4.tcp_mtu_probing", "value": "1" }
    - { "name": "net.ipv4.tcp_congestion_control", "value": "hybla" }
