---
- name: install apt packages
  apt:
    name: dnsmasq

- name: configure DHCP
  lineinfile:
    path: '/etc/dnsmasq.conf'
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
    firstmatch: true
  with_items:
    - { regexp: 'port=', line: 'port=0'}
    - { regexp: 'interface=', line: 'interface={{ lan_interface }}'}
    - { regexp: 'dhcp-range={{ lan_gateway_ip }}', line: 'dhcp-range={{ lan_dhcp_range }}'}
    - { regexp: 'dhcp-option=6', line: 'dhcp-option=6,{{ lan_gateway_ip }}' }
  notify: restart dnsmasq
