---
- name: create new chain
  command: iptables -t nat -N CLASH
  register: result
  failed_when: 'result.rc != 0 and "already exists" not in result.stderr'
  changed_when: '"already exists" not in result.stderr'

- name: configure clash ignored destination
  iptables:
    table: nat
    chain: CLASH
    protocol: tcp
    destination: '{{ item }}'
    jump: RETURN
  with_items:
    - '0.0.0.0/8'
    - '10.0.0.0/8'
    - '127.0.0.0/8'
    - '172.16.0.0/12'
    - '192.168.0.0/16'
  notify: netfilter-persistent

- name: configure clash ignored source
  iptables:
    table: nat
    chain: CLASH
    protocol: tcp
    source: '{{ item }}'
    jump: RETURN
  with_items: '{{ clash_ignored_lan_ip }}'
  notify: netfilter-persistent

- name: configure clash ignored port
  iptables:
    table: nat
    chain: CLASH
    protocol: tcp
    destination_port: '{{ item }}'
    jump: RETURN
  with_items: '{{ [redir_port] + clash_proxy_ports }}'
  notify: netfilter-persistent

- name: configure clash ignored address
  iptables:
    table: nat
    chain: CLASH
    protocol: tcp
    destination: '{{ item }}'
    jump: RETURN
  with_items: '{{ clash_proxy_address }}'
  notify: netfilter-persistent

- name: configure clash redirect
  iptables:
    table: nat
    chain: CLASH
    protocol: tcp
    to_ports: '{{ redir_port }}'
    jump: REDIRECT
  notify: netfilter-persistent

- name: redirect PREROUTING to CLASH
  iptables:
    table: nat
    chain: PREROUTING
    source: '{{ lan_gateway_cidr }}'
    protocol: tcp
    jump: CLASH
  notify: netfilter-persistent

# Firewall

- name: setup allow established
  iptables:
    table: filter
    chain: INPUT
    protocol: all
    in_interface: '{{ wan_interface }}'
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT
  notify: netfilter-persistent

- name: setup allowed icmp
  iptables:
    table: filter
    chain: INPUT
    in_interface: '{{ wan_interface }}'
    protocol: icmp
    jump: ACCEPT
  notify: netfilter-persistent

- name: setup allowed income tcp ports
  iptables:
    table: filter
    chain: INPUT
    protocol: tcp
    in_interface: '{{ wan_interface }}'
    destination_port: '{{ item }}'
    jump: ACCEPT
  with_items: '{{ allowed_imcome_ports }}'
  notify: netfilter-persistent

- name: setup allowed income udp ports
  iptables:
    table: filter
    chain: INPUT
    protocol: udp
    in_interface: '{{ wan_interface }}'
    destination_port: '{{ item }}'
    jump: ACCEPT
  with_items:
    - 16881
    - 6881
  notify: netfilter-persistent

- name: reject other packet from wan
  iptables:
    table: filter
    chain: INPUT
    protocol: all
    in_interface: '{{ wan_interface }}'
    jump: REJECT
  notify: netfilter-persistent

# Port Forwarding

- name: forwarding netdata to 80
  iptables:
    table: nat
    chain: PREROUTING
    protocol: tcp
    in_interface: '{{ lan_interface }}'
    destination: '{{ lan_gateway_ip }}'
    destination_port: 80
    jump: REDIRECT
    to_ports: 19999
  notify: netfilter-persistent

- name: forwarding DiskStation tcp ports
  iptables:
    table: nat
    chain: PREROUTING
    protocol: tcp
    in_interface: '{{ wan_interface }}'
    destination_port: '{{ item }}'
    jump: DNAT
    to_destination: '10.0.0.10'
  with_items:
    - 5000
    - 16881
  notify: netfilter-persistent

- name: forwarding DiskStation udp port
  iptables:
    table: nat
    chain: PREROUTING
    protocol: udp
    in_interface: '{{ wan_interface }}'
    destination_port: '{{ item }}'
    jump: DNAT
    to_destination: '10.0.0.10'
  with_items:
    - 16881
    - 6881
  notify: netfilter-persistent
