---
- name: add apt repository key
  apt_key:
    id: 0C49F3730359A14518585931BC711F9BA15703C6
    keyserver: 'hkp://keyserver.ubuntu.com:80'

- name: add apt repository
  apt_repository:
    repo: 'deb http://repo.mongodb.org/apt/ubuntu {{ ansible_lsb.codename|lower }}/mongodb-org/3.4 multiverse'
    update_cache: yes

- name: install apt packages
  apt:
    name: mongodb-org
