---
- name: add apt repository
  apt_repository:
    repo: 'ppa:certbot/certbot'
    update_cache: yes

- name: install apt packages
  apt:
    name: certbot

- name: issue certificates
  command: certbot certonly --webroot -w /var/www/html -d {{item}} --email {{letsencrypt_email}} --agree-tos --noninteractive
  with_items: '{{letsencrypt}}'

- name: setup cronjob
  cron:
    name: letsencrypt
    special_time: daily
    job: 'certbot renew'
