---
- hosts: all
  vars_files:
    - secrets.yml
  roles:
    - common

- hosts: forum
  vars:
    letsencrypt:
      - atom-china.org
      - hexo-china.org
      - gpg-china.org
      - git-china.org
  vars_files:
    - secrets.yml
  roles:
    - nginx
    - letsencrypt
    - docker
    - discourse

- hosts: us-w2-app1
  vars_files:
    - secrets.yml
  vars:
    letsencrypt:
      - stream.pub
  roles:
    - nginx
    - letsencrypt
    - docker
    - mongodb
