---
- hosts: all
  vars_files:
    - secrets.yml
  roles:
    - common

- hosts: sg-agent
  vars_files:
    - secrets.yml
  roles:
    - shadowsocks
    - syncthing

- hosts: us-agent
  vars_files:
    - secrets.yml
  roles:
    - shadowsocks
    - syncthing

- hosts: jp-agent
  vars_files:
    - secrets.yml
  roles:
    - shadowsocks

- hosts: forum
  vars:
    letsencrypt:
      - atom-china.org
      - hexo-china.org
      - gpg-china.org
      - git-china.org
  vars_files:
    - secrets.yml
  roles:
    - nginx
    - letsencrypt
    - docker
    - discourse
