---
- hosts: all
  vars_files:
    - secrets.yml
  roles:
    - common

- hosts: spawn
  vars_files:
    - secrets.yml
  vars:
    letsencrypt:
      - jysperm.me
  roles:
    - nginx
    - letsencrypt
