---
- hosts: all
  vars_files:
    - secrets.yml
  roles:
    - common

- hosts: spawn
  vars_files:
    - secrets.yml
  vars:
    letsencrypt:
      - jysperm.me
  roles:
    - nginx
    - letsencrypt

- hosts: us-w2-app1
  vars_files:
    - secrets.yml
  vars:
    letsencrypt:
      - stream.pub
  roles:
    - nginx
    - letsencrypt
    - docker
    - mongodb
