---
- name: create aria2 compose dir
  file:
    path: /data/docker/aria2
    state: directory

- name: upload compose file
  template:
    src: 'docker-compose.yml'
    dest: '/data/docker/aria2/docker-compose.yml'

- name: Start aria2
  command:
    cmd: docker-compose up -d
    chdir: /data/docker/aria2
